apiVersion: v1
kind: Secret
metadata:
  name: fastapi-backend-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: 'https://github.com/Mayank-Bhawsar/FastAPI_end-to-end_DevOps.git'
  username: 'Mayank-Bhawsar'
  password: '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' 
  