apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-backend-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::324330564368:role/staging-fastapi-backend-irsa-role